name: yomu_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

scripts:
  generate_controller: flutter pub run build_runner watch

dependencies:
  dio: ^2.1.13
  flutter_mobx: ^0.3.6
  mobx: ^0.4.0+1
  flutter_modular: ^0.2.1

  # Firebase
  firebase_auth: ^0.15.3+1
  firebase_analytics: ^5.0.9
  firebase_core: ^0.4.3+2
  firebase_messaging: ^6.0.9
  cloud_firestore: ^0.13.0+1

  #Icons
  font_awesome_flutter: ^8.5.0

  #Linguagem para ler
  flutter_i18n: ^0.8.3

  #Hive - salvar informações internar
  hive: ^1.3.0

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  # Animation


dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^0.4.0+1
  build_runner: ^1.7.3
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/i18n/

    #  - images/a_dot_burr.jpeg
    #  - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gelasio
      fonts:
        - asset: assets/fonts/Gelasio-Regular.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
    - family: Social
      fonts:
        - asset: assets/icons/Social.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages